det_config: "demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py"
det_checkpoint: "~/.cache/torch/hub/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth"
pose_detector_config: "configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py"
pose_detector_checkpoint: "~/.cache/torch/hub/checkpoints/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth"
pose_lifter_config: "configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/h36m/videopose3d_h36m_243frames_fullconv_supervised_cpn_ft.py"
pose_lifter_checkpoint: "~/.cache/torch/hub/checkpoints/videopose_h36m_243frames_fullconv_supervised_cpn_ft-88f5abbb_20210527.pth"
video_path: "tests/data/h36m/sample_short.mp4"
rebase_keypoint_height: true
norm_pose_2d: true
num_instances: -1
show: false
out_video_root: "vis_results"
device: "cuda:0"
det_cat_id: 1
bbox_thr: 0.9
kpt_thr: 0.3
use_oks_tracking: true
tracking_thr: 0.3
radius: 8
thickness: 2
